version: "3.8"

services:
  techo_delivery_backend:
    image: webdevops/php-dev:7.4-alpine
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "8080:80"
    volumes:
      - "./:/app"
    depends_on:
      - techo_delivery_backend

  composer:
    restart: "no"
    image: composer
    command: install --ignore-platform-reqs
    working_dir: /app
    volumes:
      - "./:/app"